Adding files
ansible-collections/ansible.network pull request #1
Opened 2020-10-08 18:31 UTC by GomathiselviS

Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/677

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2020-10-08 20:29 UTC, GomathiselviS commented
recheck

2020-10-09 16:21 UTC, pabelanger commented
recheck

2020-10-09 17:05 UTC, pabelanger commented
recheck

2020-10-12 19:49 UTC, GomathiselviS commented
recheck

2021-05-17 14:10 UTC, rohitthakur2590 requested changes

2021-05-17 14:10 UTC, rohitthakur2590 commented on requirements.txt
> +ansible
this whole file could be deleted

2021-05-17 14:10 UTC, rohitthakur2590 commented on tox.ini
> +  flake8 {posargs}
- we don't have any code so we can remove black
- we can remove flake as well as we don't have any python

2021-05-17 14:10 UTC, rohitthakur2590 commented on tox.ini
> +exclude = .git,.tox,tests/unit/compat/
not required

2021-05-17 15:03 UTC, GomathiselviS commented
recheck

2021-05-17 16:15 UTC, pabelanger commented on bindep.txt
> +# This is a cross-platform list tracking distribution packages needed by tests;
I don't think we need this file

2021-05-17 17:08 UTC, rohitthakur2590 commented on bindep.txt
> +# This is a cross-platform list tracking distribution packages needed by tests;
++

2021-05-17 17:09 UTC, rohitthakur2590 commented on plugins/README.md
> +# Collections Plugins Directory
@GomathiselviS  Yes, I think it better to remove this. IMO we are good with the existing README.md

2021-05-17 17:26 UTC, rohitthakur2590 approved these changes

2021-05-17 18:10 UTC, pabelanger commented on tox.ini
> +[testenv:linters]
please add tox-linters jobs to ansible.network collection

2021-05-17 19:38 UTC, merged